version: '2'
# Simple single server setup

services:
  appvol:
    image: ezsystems/ezplatform_volume:latest

  web:
    image: nginx:stable
    volumes_from:
     - appvol
    ports:
     - "8080:80"
    environment:
     - SYMFONY_ENV
     - MAX_BODY_SIZE=20
     - FASTCGI_PASS=phpfpm:9000
     - TIMEOUT=190
     - DOCKER0NET
    command: /bin/bash -c "cd /var/www && cp -a doc/nginx/ez_params.d /etc/nginx && bin/vhost.sh --template-file=doc/nginx/vhost.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  db:
    image: mariadb:10.0
    volumes:
     - ./database_character_set.sh:/docker-entrypoint-initdb.d/database_character_set.sh
    environment:
     - MYSQL_ROOT_PASSWORD=mysecretrootpassword
     - MYSQL_USER=$DATABASE_USER
     - MYSQL_PASSWORD=$DATABASE_PASSWORD
     - MYSQL_DATABASE=$DATABASE_NAME
     - TERM=dumb

  phpfpm:
    image: ezsystems/php:7.0-v0.4
    depends_on:
     - db
    volumes_from:
     - appvol
    environment:
     - SYMFONY_ENV
     - SYMFONY_DEBUG
     - DATABASE_USER
     - DATABASE_PASSWORD
     - DATABASE_NAME
     - DATABASE_HOST=db
